name: Deploy to Vercel
on:
  push:
    branches:
      - main
jobs:
  test: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: install dependancies
        run: yarn install

      - name: test
        run: yarn test